export const SEARCH_ALBUMS_BY_TITLE = 'SEARCH_ALBUMS_BY_TITLE';
export const LOAD_SAVED_ALBUMS = 'LOAD_ALBUMS_FROM_LIBRARY';
export const SAVE_ALBUM = 'SAVE_ALBUM';
export const REMOVE_ALBUM = 'REMOVE_ALBUM';